name: tempus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^7.0.1
  purchases_flutter: ^8.4.5
  provider: ^6.1.2
  flutter_settings_ui: ^3.0.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - audio/Bell/downbeat.wav
    - audio/Bell/subdivision.wav
    - audio/Digital/downbeat.wav
    - audio/Digital/subdivision.wav
    - audio/Sine/downbeat.wav
    - audio/Sine/subdivision.wav
    - audio/Square/downbeat.wav
    - audio/Square/subdivision.wav
    - audio/Tambourine/downbeat.wav
    - audio/Tambourine/subdivision.wav
  uses-material-design: true
