name: tempus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^7.0.1
  purchases_flutter: ^8.4.5
  provider: ^6.1.2
  flutter_settings_ui: ^3.0.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - audio/free/bell/downbeat.wav
    - audio/free/bell/subdivision.wav
    - audio/free/digital/downbeat.wav
    - audio/free/digital/subdivision.wav
    - audio/free/sine/downbeat.wav
    - audio/free/sine/subdivision.wav
    - audio/free/square/downbeat.wav
    - audio/free/square/subdivision.wav
    - audio/free/tambourine/downbeat.wav
    - audio/free/tambourine/subdivision.wav
    - audio/premium/bell/downbeat.wav
    - audio/premium/bell/subdivision.wav
    - audio/premium/block/downbeat.wav
    - audio/premium/block/subdivision.wav
    - audio/premium/castanet/downbeat.wav
    - audio/premium/castanet/subdivision.wav
    - audio/premium/clap/downbeat.wav
    - audio/premium/clap/subdivision.wav
    - audio/premium/glass/downbeat.wav
    - audio/premium/glass/subdivision.wav
    - audio/premium/snap/downbeat.wav
    - audio/premium/snap/subdivision.wav
    - audio/premium/square/downbeat.wav
    - audio/premium/square/subdivision.wav
    - audio/premium/tick/downbeat.wav
    - audio/premium/tick/subdivision.wav
    - audio/premium/weird/downbeat.wav
    - audio/premium/weird/subdivision.wav
    - audio/premium/whistle/downbeat.wav
    - audio/premium/whistle/subdivision.wav
  uses-material-design: true
