name: tempus
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.3+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^7.0.1
  purchases_flutter: ^8.4.5
  provider: ^6.1.2
  flutter_settings_ui: ^3.0.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/audio/free/bell/beat.wav
    - assets/audio/free/bell/downbeat.wav
    - assets/audio/free/bell/inner_beat.wav
    - assets/audio/free/digital/beat.wav
    - assets/audio/free/digital/downbeat.wav
    - assets/audio/free/digital/inner_beat.wav
    - assets/audio/free/sine/beat.wav
    - assets/audio/free/sine/downbeat.wav
    - assets/audio/free/sine/inner_beat.wav
    - assets/audio/free/square/beat.wav
    - assets/audio/free/square/downbeat.wav
    - assets/audio/free/square/inner_beat.wav
    - assets/audio/free/tambourine/beat.wav
    - assets/audio/free/tambourine/downbeat.wav
    - assets/audio/free/tambourine/inner_beat.wav
    - assets/audio/premium/bell/beat.wav
    - assets/audio/premium/bell/downbeat.wav
    - assets/audio/premium/bell/inner_beat.wav
    - assets/audio/premium/block/beat.wav
    - assets/audio/premium/block/downbeat.wav
    - assets/audio/premium/block/inner_beat.wav
    - assets/audio/premium/castanet/beat.wav
    - assets/audio/premium/castanet/downbeat.wav
    - assets/audio/premium/castanet/inner_beat.wav
    - assets/audio/premium/clap/beat.wav
    - assets/audio/premium/clap/downbeat.wav
    - assets/audio/premium/clap/inner_beat.wav
    - assets/audio/premium/glass/beat.wav
    - assets/audio/premium/glass/downbeat.wav
    - assets/audio/premium/glass/inner_beat.wav
    - assets/audio/premium/snap/beat.wav
    - assets/audio/premium/snap/downbeat.wav
    - assets/audio/premium/snap/inner_beat.wav
    - assets/audio/premium/square/beat.wav
    - assets/audio/premium/square/downbeat.wav
    - assets/audio/premium/square/inner_beat.wav
    - assets/audio/premium/tick/beat.wav
    - assets/audio/premium/tick/downbeat.wav
    - assets/audio/premium/tick/inner_beat.wav
    - assets/audio/premium/weird/beat.wav
    - assets/audio/premium/weird/downbeat.wav
    - assets/audio/premium/weird/inner_beat.wav
    - assets/audio/premium/whistle/beat.wav
    - assets/audio/premium/whistle/downbeat.wav
    - assets/audio/premium/whistle/inner_beat.wav
  fonts:
    - family: NotoMusic
      fonts:
        - asset: assets/fonts/NotoMusic.ttf
    - family: SFMono
      fonts:
        - asset: assets/fonts/SFMono.otf
  uses-material-design: true
